Update polkadot-v0.9.5 deps
open-web3-stack/open-runtime-module-library pull request #521
Opened 2021-06-15 02:51 UTC by zjb0807

Closes: #519

2021-06-15 03:11 UTC, shaunxw reviewed
v0.9.5 is not released yet

2021-06-15 03:18 UTC, xlc commented
v0.9.5 branch is created and we want to start using it ASAP

2021-06-15 03:20 UTC, xlc approved these changes

2021-06-15 03:25 UTC, shaunxw commented
> v0.9.5 branch is created and we want to start using it ASAP

Okay, though it would be painful, as the deps branch update will be expected to break our compiling/CI from time to time and block our work.

2021-06-15 03:44 UTC, xlc commented
it is not master, so hopefully won't be too bad

2021-06-17 09:50 UTC, xlc requested changes

2021-06-17 09:50 UTC, xlc commented on Cargo.dev.toml
> +frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "c666a251691300c1651075a3b59ba1cf59c5a664" }
Need to bump Substrate to `3bb42b9aaba65e956aea7aaef2c2fb3468fa3aaf`

2021-06-17 10:05 UTC, xlc approved these changes

2021-06-17 14:25 UTC, merged